package io.internship.learn.hashcode;

public class Person {

    private String name;
    private String address;
    private int age;


    /**
     * Both equals() and hashCode() are generated by using IDE default generator
     *
     * We can also use {Lombok} project to Generate them
     *
     * @param o
     * @return
     */

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Person person = (Person) o;

        if (age != person.age) return false;
        if (!name.equals(person.name)) return false;
        return address.equals(person.address);
    }


    /**
     * We can what we want to implement the Login of hashCode but we need to preserve the constraints of HashCode
     * <p>
     * The hashCode unique for each Object and the same for each creation
     * <p>
     * <p>
     * if we have to equals object always gives the same hashCode
     *
     * @return
     */
    @Override
    public int hashCode() {
        int result = name.hashCode();
        result = 31 * result + address.hashCode();
        result = 31 * result + age;
        return result;
    }
}
